# Generated by Django 6.0.5 on 2026-05-09 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='alert',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('warning', 'Warning'), ('suspicious', 'Suspicious'), ('critical', 'Critical')], default='warning', max_length=20),
        ),
        migrations.AddField(
            model_name='evidencelog',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='evidence_annotated/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('suspicious_head_movement', 'Suspicious Head Movement'), ('looking_left_right', 'Looking Left/Right'), ('face_missing', 'Face Missing'), ('multiple_faces', 'Multiple Faces'), ('abnormal_body_movement', 'Abnormal Body Movement'), ('unknown_person', 'Unknown Person Detected')], max_length=50),
        ),
        migrations.CreateModel(
            name='BehaviourLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Normal', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('head_pose', models.JSONField(null=True)),
                ('gaze_direction', models.CharField(max_length=50, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_logs', to='api.student')),
            ],
        ),
    ]
