# Generated by Django 6.0.5 on 2026-05-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_alert_options_alert_metadata_alert_severity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("suspicious_head_movement", "Suspicious Head Movement"),
                    ("looking_left_right", "Looking Left/Right"),
                    ("face_missing", "Face Missing"),
                    ("multiple_faces", "Multiple Faces"),
                    ("abnormal_body_movement", "Abnormal Body Movement"),
                    ("unknown_person", "Unknown Person Detected"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("warning", "Warning"),
                    ("suspicious", "Suspicious"),
                    ("critical", "Critical"),
                ],
                db_index=True,
                default="warning",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="behaviourlog",
            name="status",
            field=models.CharField(db_index=True, default="Normal", max_length=20),
        ),
        migrations.AlterField(
            model_name="behaviourlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
