# Generated by Django 6.0.5 on 2026-05-10 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alert_alert_type_alter_alert_severity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('suspicious_head_movement', 'Suspicious Head Movement'), ('looking_left_right', 'Looking Left/Right'), ('face_missing', 'Face Missing'), ('multiple_faces', 'Multiple Faces'), ('suspicious_body_movement', 'Suspicious Body Movement'), ('abnormal_body_movement', 'Abnormal Body Movement'), ('unknown_person', 'Unknown Person Detected')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='uploaded_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('total_frames', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('suspicious', 'Suspicious'), ('critical', 'Critical')], db_index=True, default='warning', max_length=20)),
                ('timestamp_in_video', models.FloatField(db_index=True)),
                ('frame_number', models.IntegerField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('reason', models.TextField()),
                ('behaviour_status', models.CharField(default='Normal', max_length=20)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='video_evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_alerts', to='api.uploadedvideo')),
            ],
            options={
                'ordering': ['timestamp_in_video'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_frames', models.IntegerField(default=0)),
                ('processed_frames', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('normal_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('uploaded_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='api.uploadedvideo')),
            ],
        ),
    ]
