# Generated by Django 6.0.5 on 2026-05-10 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_alert_alert_type_uploadedvideo_videoalert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEvidenceFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp_in_video', models.FloatField()),
                ('image', models.ImageField(upload_to='video_evidence_original/')),
                ('overlay_image', models.ImageField(upload_to='video_evidence_annotated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_frames', to='api.videoalert')),
                ('uploaded_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_frames', to='api.uploadedvideo')),
            ],
        ),
    ]
