# Generated by Django 6.0.5 on 2026-05-10 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_videoevidenceframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoevidenceframe',
            name='alert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_frame', to='api.videoalert'),
        ),
        migrations.AlterField(
            model_name='videoevidenceframe',
            name='image',
            field=models.ImageField(upload_to='video_evidence/original/'),
        ),
        migrations.AlterField(
            model_name='videoevidenceframe',
            name='overlay_image',
            field=models.ImageField(blank=True, null=True, upload_to='video_evidence/annotated/'),
        ),
    ]
