# Generated by Django 6.0.5 on 2026-05-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_videoevidenceframe_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('suspicious_head_movement', 'Suspicious Head Movement'), ('looking_left_right', 'Looking Left/Right'), ('face_missing', 'Face Missing'), ('multiple_faces', 'Multiple Faces'), ('suspicious_body_movement', 'Suspicious Body Movement'), ('abnormal_body_movement', 'Abnormal Body Movement'), ('unknown_person', 'Unknown Person Detected'), ('eyes_closed', 'Eyes Closed / Drowsy')], db_index=True, max_length=50),
        ),
    ]
